FROM node:20 -alpine as frontend-builder
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN nvm install
COPY frontend ./
RUN nvm run build 


FROM node:20 -alpine
WORKDIR /app/backend
COPY backend/package*.json ./
RUN nvm install
COPY backend ./

COPY --from=frontend-builder /app/frontend/dist /app/frontend/dist

EXPOSE 8080

CMD ["nvm", "start"]
